version: '3.8'


services:
  postgres:
    image: postgres:17
    container_name: postgres-container
    env_file:
     - ./docker/postgres/.env
    volumes:
     - crewai_postgres_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    networks:
     - crewai_network
    restart: unless-stopped
  
  # Define other services like qdrant here
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    environment:
      QDRANT__STORAGE_PATH: /qdrant/QDRANT__STORAGE_PATH
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
    volumes:
     - crewai_qdrant_data:/qdrant/QDRANT__STORAGE_PATH
    ports:
     - "6333:6333"
     - "6334:6334"
    networks:
     - crewai_network
    restart: unless-stopped

volumes:
  crewai_postgres_data:
    driver: local
  crewai_qdrant_data:
    driver: local

networks:
  crewai_network:
    driver: bridge